version: "2.18.1"

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: 1001:1001
    restart: unless-stopped
    volumes:
      - /home/dlp-prod-zambia/observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/dlp-prod-zambia/observability/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=
    ports:
      - 3000:3000

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
      - /home/dlp-prod-zambia/observability/loki/promtail-config.yml:/etc/promtail/promtail-config.yml
    command:
      - '-config.file=/etc/promtail/promtail-config.yml'
      - '-config.expand-env=true'

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    volumes:
      - /home/dlp-prod-zambia/observability/loki/loki-config.yml:/etc/loki/loki-config.yml
    command:
      - '-config.file=/etc/loki/loki-config.yml'
      - '-config.expand-env=true'
    ports:
      - 3100:3100


volumes:
  grafana_data:
