global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['10.241.108.152:9100', '10.241.108.155:9100', '10.241.108.151:9100', '10.241.108.153:9100', '10.241.105.151:9100']

